inherit_from:
  - .rubocop_todo.yml

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200
  Exclude:
   - 'test/**/*'

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Metrics/LineLength:
  Enabled: false
