query($search: String, $first: Int, $last: Int) {
  cves(search: $search, first: $first, last: $last) {
    totalCount
    nodes {
      id
      refId
      refUrl
      hasErrata
      definitionId
      hosts {
        nodes {
          id
          name
        }
      }
    }
  }
}
