#import "./currentUserAttributes.gql"

query($id: String!) {
  ovalPolicy(id: $id) {
    id
    name
    period
    cronLine
    weekday
    dayOfMonth
    description
    meta {
      canEdit
    }
    hostgroups {
      nodes {
        id
        descendants {
          nodes {
            id
          }
        }
      }
    }
  }
  currentUser {
    ...CurrentUserAttributes
  }
}
