#import "./currentUserAttributes.gql"

query($first: Int, $last: Int) {
  ovalPolicies(first: $first, last: $last) {
    totalCount
    nodes {
      id
      name
      ovalContent {
        name
      }
    }
  }
  currentUser {
    ...CurrentUserAttributes
  }
}
